
call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'sonph/onehalf', { 'rtp': 'vim' }
Plug 'preservim/nerdtree'
Plug 'tpope/vim-fugitive'
" Plug 'rakr/vim-one'

call plug#end()

" let g:airline_theme='one'
" colorscheme one

" set background=dark

set guifont=Source\ Code\ Pro\ For\ Powerline:h13
colorscheme onehalfdark

set cursorline
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='onehalfdark'

set runtimepath^=~/.vim/bundle/ctrlp.vim
let g:ctrlp_follow_symlinks = 1
let g:ctrlp_working_path_mode = 'r'
let g:ctrlp_map = '<D-t>'

nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>
